### ISSUE TITLE
 cannot open <datasets/DTexture/processed/meta/WavingFlag_train_meta.t7>

### ISSUE THREAD

**Issue by liupingping123** [Yijunmaverick/FlowGrounded-VideoPrediction#1]
CUDA_VISIBLE_DEVICES=0 th test.lua --dataRoot da
tasets/DTexture
/home/lab330/torch/install/bin/luajit: /home/lab330/torch/install/share/lua/5.1/trepl/init.lua:389: cannot open <datasets/DTexture/processed/meta/WavingFlag_train_meta.t7> in mode r  at /home/lab330/torch/pkg/torch/lib/TH/THDiskFile.c:673
stack traceback:
	[C]: in function 'error'
	/home/lab330/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	test.lua:193: in main chunk
	[C]: in function 'dofile'
	...b330/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

When I follow the instruction and use provided models learned on the WavingFlag data for testing, there is an error.
I wonder if WavingFlag_train_meta.t7 is lacked or I should change the model name in somewhere of the test code.

**Comment by Yijunmaverick** [comment]
Please check the `Preparation` in `Readme`. Basically you need to generate the meta data first. This is convenient for both training and testing a dataset. You may change it to testing with a single image only.

**Comment by liupingping123** [comment]
Thank you very much for your answer.

**Comment by HaoWangXiDian** [comment]
where could I get waving flag and floating cloud dataset? @Yijunmaverick @liupingping123

**Comment by liupingping123** [comment]
> where could I get waving flag and floating cloud dataset? @Yijunmaverick @liupingping123

Sorry I used my own dataset.

**Comment by Kamel-schbock** [comment]
Hey @liupingping123 
I have some question if you run this project sucessfully. I think the author doesn't answer the previous opened issues.
I am trying to preprocess my own datasets as your instructions, but it doesn't work correctly.
Can you please help me?
I put my own raw video in the following (datasets/DTexture/raw) and when i run (sh data_process.sh) i get the following error:

Traceback (most recent call last):
File "collectinfo.py", line 13, in
for foldername in os.listdir(folder1):
OSError: [Errno 2] No such file or directory: './DTexture/raw/WavingFlag/'

I know i should change WavingFlag, but what should i change in the code (ex: collectinfo.py) to make it work? I tried my best but not succeeded.
Thanks
